set(PDJE_UTIL_SOURCES
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/ai/AI.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/ai/beat_this/BeatThis.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/ai/beat_this/BeatThisFrontend.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/ai/beat_this/BeatThisMelBackend.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/ai/beat_this/BeatThisInference.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/ai/beat_this/BeatThisPostprocessor.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/db/backends/RocksDbBackend.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/stft/STFT_Parallel.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/stft/BackendLess.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/stft/detail/SerialBackend.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/stft/detail/OpenclBackend.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/stft/detail/OpenCL_Loader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/stft/detail/PDJE_Parallel_Runtime_Loader.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/image/WaveformWebp.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/image/detail/WaveformWebpEncoder.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/image/detail/WaveformWebpPlanBuilder.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/image/detail/WaveformWebpRasterizer.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/include/util/function/image/detail/WaveformWebpProcessor.cpp
)

set(PDJE_UTIL_PRIVATE_INCLUDE
  ${CMAKE_CURRENT_SOURCE_DIR}/GenCodes/OKL/GenOut/OpenCL
  ${CMAKE_CURRENT_SOURCE_DIR}/GenCodes/OKL/GenOut/SERIAL
)
