

if(PDJE_DYNAMIC)
  set(PDJE_LOG_RUNTIME_LIBRARY_TYPE SHARED)
else()
  set(PDJE_LOG_RUNTIME_LIBRARY_TYPE STATIC)
endif()


add_library(
  PDJE_LOG_RUNTIME
  ${PDJE_LOG_RUNTIME_LIBRARY_TYPE}
  ${CMAKE_CURRENT_SOURCE_DIR}/include/global/PDJE_LOG_SETTER.cpp)

target_include_directories(PDJE_LOG_RUNTIME PUBLIC ${PDJE_INCLUDE_GLOBAL})

if(PDJE_LOG_STRICT_EXPLICIT_INIT)
  target_compile_definitions(PDJE_LOG_RUNTIME PRIVATE PDJE_LOG_STRICT_EXPLICIT_INIT)
endif()

if(NOT WIN32)
  set_target_properties(PDJE_LOG_RUNTIME PROPERTIES
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN YES
  )
endif()

AddDynamicDef(PDJE_LOG_RUNTIME)

setSpdlogReqLib(PDJE_LOG_RUNTIME)
PDJE_COMPILE_OPTION(PDJE_LOG_RUNTIME)
SET_PROPERTIES(PDJE_LOG_RUNTIME)

