
add_executable(
PDJE_MODULE_INPUT_PROCESS 
${globalSource}  
${PDJE_INPUT_SUBPROC_SRC}
${IPC_SRC_EXPORT}
)

# target_include_directories(PDJE_MODULE_INPUT_PROCESS PUBLIC ${PDJE_INCLUDE_INPUT_SUBPROC} ${PDJE_INCLUDE_IPC})
target_link_libraries(PDJE_MODULE_INPUT_PROCESS PRIVATE IPC_OBJ CRYPTO_OBJ PDJE_LOG_RUNTIME)
target_link_libraries(PDJE_MODULE_INPUT_PROCESS PUBLIC IPC_INCLUDE CRYPTO_INCLUDE INPUT_SUBPROC_INCLUDE)

# AddDynamicDef(PDJE_MODULE_INPUT_PROCESS)
DynamicInnerFlag(PDJE_MODULE_INPUT_PROCESS)
PDJE_COMPILE_OPTION(PDJE_MODULE_INPUT_PROCESS)
PDJE_INPUT_LINK_LIB(PDJE_MODULE_INPUT_PROCESS)
target_link_libraries(PDJE_MODULE_INPUT_PROCESS PRIVATE PDJE_LOG_RUNTIME)
setSpdlogReqLib(PDJE_MODULE_INPUT_PROCESS)
# setPdjeLogRuntimeReqLib(PDJE_MODULE_INPUT_PROCESS)
setLibreMIDIReqLib(PDJE_MODULE_INPUT_PROCESS)
SET_PROPERTIES(PDJE_MODULE_INPUT_PROCESS)
setBotanReqLib(PDJE_MODULE_INPUT_PROCESS)

add_custom_command(
OUTPUT ${RT_HASH_HEADER}
COMMAND ${CMAKE_COMMAND}
    -DRT_BIN=$<TARGET_FILE:PDJE_MODULE_INPUT_PROCESS>
    -DOUT_HDR=${RT_HASH_HEADER}
    -P ${CMAKE_CURRENT_SOURCE_DIR}/cmakes/GenRTHASH.cmake
DEPENDS PDJE_MODULE_INPUT_PROCESS $<TARGET_FILE:PDJE_MODULE_INPUT_PROCESS>

VERBATIM
USES_TERMINAL
)

add_custom_target(gen_RT_HASH ALL DEPENDS ${RT_HASH_HEADER})

add_dependencies(INPUT_OBJ gen_RT_HASH)
target_include_directories(INPUT_OBJ PUBLIC ${RT_HASH_HEADER_INCLUDE})
