
add_executable(
PDJE_MODULE_INPUT_PROCESS 
${globalSource}  
${PDJE_INPUT_SUBPROC_SRC}
${IPC_SRC_EXPORT}
)

target_include_directories(PDJE_MODULE_INPUT_PROCESS PUBLIC ${PDJE_INCLUDE_INPUT_SUBPROC} ${PDJE_INCLUDE_IPC})
target_link_libraries(PDJE_MODULE_INPUT_PROCESS PUBLIC IPC_OBJ )
# AddDynamicDef(PDJE_MODULE_INPUT_PROCESS)
DynamicInnerFlag(PDJE_MODULE_INPUT_PROCESS)
PDJE_COMPILE_OPTION(PDJE_MODULE_INPUT_PROCESS)
PDJE_INPUT_LINK_LIB(PDJE_MODULE_INPUT_PROCESS)
target_link_libraries(PDJE_MODULE_INPUT_PROCESS PUBLIC PDJE_LOG_RUNTIME)
# setSpdlogReqLib(PDJE_MODULE_INPUT_PROCESS)
# setPdjeLogRuntimeReqLib(PDJE_MODULE_INPUT_PROCESS)
setLibreMIDIReqLib(PDJE_MODULE_INPUT_PROCESS)
SET_PROPERTIES(PDJE_MODULE_INPUT_PROCESS)
setBotanReqLib(PDJE_MODULE_INPUT_PROCESS)
set(RT_HASH_HEADER ${CMAKE_CURRENT_BINARY_DIR}/generated/PDJE_INPUT_PROCESS_HASH.hpp)
set(RT_HASH_HEADER_INCLUDE ${CMAKE_CURRENT_BINARY_DIR}/generated/)

add_custom_command(
OUTPUT ${RT_HASH_HEADER}
COMMAND ${CMAKE_COMMAND}
    -DRT_BIN=$<TARGET_FILE:PDJE_MODULE_INPUT_PROCESS>
    -DOUT_HDR=${RT_HASH_HEADER}
    -P ${CMAKE_CURRENT_SOURCE_DIR}/cmakes/GenRTHASH.cmake
DEPENDS PDJE_MODULE_INPUT_PROCESS $<TARGET_FILE:PDJE_MODULE_INPUT_PROCESS>
BYPRODUCTS ${RT_HASH_HEADER}
VERBATIM
USES_TERMINAL
)

add_custom_target(gen_RT_HASH ALL DEPENDS ${RT_HASH_HEADER})