
function(LinuxSetAtomic targetName)
  if(LINUX)
    target_link_libraries(${targetName} PUBLIC atomic)
    target_link_options(${targetName} PUBLIC -Wl,-z,defs)
  endif()
endfunction()

function(LinuxSetAudioLibs targetName)
  if(LINUX)
    target_link_libraries(${targetName} PUBLIC asound)
  endif()
endfunction(LinuxSetAudioLibs )


function(setCoreReqs targetName)
  target_include_directories(${targetName} PUBLIC ${PDJE_INCLUDE_CORE})
  AddDynamicDef(${targetName})
  
  target_link_libraries(${targetName} PUBLIC nlohmann_json::nlohmann_json)
  setSqliteReqLib(${targetName})
  setRocksDBReqLib(${targetName})
  setSpdlogReqLib(${targetName})
  setPdjeLogRuntimeReqLib(${targetName})
  setCapnpReqLib(${targetName})
  setLibgit2ReqLib(${targetName})
  setHighwayReqLib(${targetName})
  pdje_halide_attach_to_target(${targetName})
  LinuxSetAtomic(${targetName})
  LinuxSetAudioLibs(${targetName})
  PDJE_COMPILE_OPTION(${targetName})
  setBotanReqLib(${targetName})
  SET_PROPERTIES(${targetName})
endfunction(setCoreReqs)


function(setInputReqs targetName)
  AddDynamicDef(${targetName})
  
  if(WIN32)
    add_dependencies(${targetName} gen_RT_HASH)
    target_include_directories(${targetName} PUBLIC ${RT_HASH_HEADER_INCLUDE})
  endif()
  target_include_directories(${targetName} PUBLIC ${PDJE_INCLUDE_INPUT_MAINPROC} )
  setSpdlogReqLib(${targetName})
  setPdjeLogRuntimeReqLib(${targetName})
  setBotanReqLib(${targetName})
  PDJE_INPUT_LINK_LIB(${targetName})
  pdje_halide_attach_to_target(${targetName})
  LinuxSetAtomic(${targetName})
  
  SET_PROPERTIES(${targetName})
  PDJE_COMPILE_OPTION(${targetName})
  setLibreMIDIReqLib(${targetName})
endfunction(setInputReqs)

function(setJudgeReqs targetName)
  AddDynamicDef(${targetName})
  
  if(WIN32)
    add_dependencies(${targetName} gen_RT_HASH)
    target_include_directories(${targetName} PUBLIC ${RT_HASH_HEADER_INCLUDE})
  endif()
  target_include_directories(${targetName} PUBLIC ${PDJE_INCLUDE_INPUT_MAINPROC} ${PDJE_INCLUDE_JUDGE})
  setSpdlogReqLib(${targetName})
  setPdjeLogRuntimeReqLib(${targetName})
  setCapnpReqLib(${targetName})
  setBotanReqLib(${targetName})
  pdje_halide_attach_to_target(${targetName})
  LinuxSetAtomic(${targetName})
  SET_PROPERTIES(${targetName})
  PDJE_COMPILE_OPTION(${targetName})
  setLibreMIDIReqLib(${targetName})
endfunction(setJudgeReqs)