//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class commit : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal commit(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(commit obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(commit obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~commit() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pdje_POLYGLOTPINVOKE.delete_commit(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_git_commit commitPointer {
    set {
      pdje_POLYGLOTPINVOKE.commit_commitPointer_set(swigCPtr, SWIGTYPE_p_git_commit.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pdje_POLYGLOTPINVOKE.commit_commitPointer_get(swigCPtr);
      SWIGTYPE_p_git_commit ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_git_commit(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_git_oid commitID {
    set {
      pdje_POLYGLOTPINVOKE.commit_commitID_set(swigCPtr, SWIGTYPE_p_git_oid.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pdje_POLYGLOTPINVOKE.commit_commitID_get(swigCPtr);
      SWIGTYPE_p_git_oid ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_git_oid(cPtr, false);
      return ret;
    } 
  }

  public string msg {
    set {
      pdje_POLYGLOTPINVOKE.commit_msg_set(swigCPtr, value);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pdje_POLYGLOTPINVOKE.commit_msg_get(swigCPtr);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public commit() : this(pdje_POLYGLOTPINVOKE.new_commit__SWIG_0(), true) {
  }

  public commit(SWIGTYPE_p_git_oid commitID, SWIGTYPE_p_git_repository rep) : this(pdje_POLYGLOTPINVOKE.new_commit__SWIG_1(SWIGTYPE_p_git_oid.getCPtr(commitID), SWIGTYPE_p_git_repository.getCPtr(rep)), true) {
    if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
  }

  public commit(string commitMSG, SWIGTYPE_p_git_repository rep) : this(pdje_POLYGLOTPINVOKE.new_commit__SWIG_2(commitMSG, SWIGTYPE_p_git_repository.getCPtr(rep)), true) {
    if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
  }

}
