//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class EDIT_ARG_MIX : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal EDIT_ARG_MIX(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EDIT_ARG_MIX obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(EDIT_ARG_MIX obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~EDIT_ARG_MIX() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pdje_POLYGLOTPINVOKE.delete_EDIT_ARG_MIX(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public TypeEnum type {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_type_set(swigCPtr, (int)value);
    } 
    get {
      TypeEnum ret = (TypeEnum)pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_type_get(swigCPtr);
      return ret;
    } 
  }

  public DetailEnum details {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_details_set(swigCPtr, (int)value);
    } 
    get {
      DetailEnum ret = (DetailEnum)pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_details_get(swigCPtr);
      return ret;
    } 
  }

  public int ID {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_ID_set(swigCPtr, value);
    } 
    get {
      int ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_ID_get(swigCPtr);
      return ret;
    } 
  }

  public string first {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_first_set(swigCPtr, value);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_first_get(swigCPtr);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string second {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_second_set(swigCPtr, value);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_second_get(swigCPtr);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string third {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_third_set(swigCPtr, value);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_third_get(swigCPtr);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public long beat {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_beat_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_beat_get(swigCPtr);
      return ret;
    } 
  }

  public long subBeat {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_subBeat_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_subBeat_get(swigCPtr);
      return ret;
    } 
  }

  public long separate {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_separate_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_separate_get(swigCPtr);
      return ret;
    } 
  }

  public long Ebeat {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_Ebeat_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_Ebeat_get(swigCPtr);
      return ret;
    } 
  }

  public long EsubBeat {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_EsubBeat_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_EsubBeat_get(swigCPtr);
      return ret;
    } 
  }

  public long Eseparate {
    set {
      pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_Eseparate_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.EDIT_ARG_MIX_Eseparate_get(swigCPtr);
      return ret;
    } 
  }

  public EDIT_ARG_MIX() : this(pdje_POLYGLOTPINVOKE.new_EDIT_ARG_MIX(), true) {
  }

}
