//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MusicOnDeck : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MusicOnDeck(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MusicOnDeck obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MusicOnDeck obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MusicOnDeck() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pdje_POLYGLOTPINVOKE.delete_MusicOnDeck(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool play {
    set {
      pdje_POLYGLOTPINVOKE.MusicOnDeck_play_set(swigCPtr, value);
    } 
    get {
      bool ret = pdje_POLYGLOTPINVOKE.MusicOnDeck_play_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_Decoder dec {
    set {
      pdje_POLYGLOTPINVOKE.MusicOnDeck_dec_set(swigCPtr, SWIGTYPE_p_Decoder.getCPtr(value));
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Decoder ret = new SWIGTYPE_p_Decoder(pdje_POLYGLOTPINVOKE.MusicOnDeck_dec_get(swigCPtr), true);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public FXControlPannel fxP {
    set {
      pdje_POLYGLOTPINVOKE.MusicOnDeck_fxP_set(swigCPtr, FXControlPannel.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = pdje_POLYGLOTPINVOKE.MusicOnDeck_fxP_get(swigCPtr);
      FXControlPannel ret = (cPtr == global::System.IntPtr.Zero) ? null : new FXControlPannel(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_std__optionalT_soundtouch__SoundTouch_t st {
    set {
      pdje_POLYGLOTPINVOKE.MusicOnDeck_st_set(swigCPtr, SWIGTYPE_p_std__optionalT_soundtouch__SoundTouch_t.getCPtr(value));
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_std__optionalT_soundtouch__SoundTouch_t ret = new SWIGTYPE_p_std__optionalT_soundtouch__SoundTouch_t(pdje_POLYGLOTPINVOKE.MusicOnDeck_st_get(swigCPtr), true);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public MusicOnDeck() : this(pdje_POLYGLOTPINVOKE.new_MusicOnDeck(), true) {
  }

}
