//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class MusicArgs : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal MusicArgs(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(MusicArgs obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(MusicArgs obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~MusicArgs() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pdje_POLYGLOTPINVOKE.delete_MusicArgs(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string bpm {
    set {
      pdje_POLYGLOTPINVOKE.MusicArgs_bpm_set(swigCPtr, value);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pdje_POLYGLOTPINVOKE.MusicArgs_bpm_get(swigCPtr);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public long beat {
    set {
      pdje_POLYGLOTPINVOKE.MusicArgs_beat_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.MusicArgs_beat_get(swigCPtr);
      return ret;
    } 
  }

  public long subBeat {
    set {
      pdje_POLYGLOTPINVOKE.MusicArgs_subBeat_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.MusicArgs_subBeat_get(swigCPtr);
      return ret;
    } 
  }

  public long separate {
    set {
      pdje_POLYGLOTPINVOKE.MusicArgs_separate_set(swigCPtr, value);
    } 
    get {
      long ret = pdje_POLYGLOTPINVOKE.MusicArgs_separate_get(swigCPtr);
      return ret;
    } 
  }

  public MusicArgs() : this(pdje_POLYGLOTPINVOKE.new_MusicArgs(), true) {
  }

}
