//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class pdje_POLYGLOTPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="SWIGRegisterExceptionCallbacks_pdje_POLYGLOT")]
    public static extern void SWIGRegisterExceptionCallbacks_pdje_POLYGLOT(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_pdje_POLYGLOT")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_pdje_POLYGLOT(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_pdje_POLYGLOT(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_pdje_POLYGLOT(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="SWIGRegisterStringCallback_pdje_POLYGLOT")]
    public static extern void SWIGRegisterStringCallback_pdje_POLYGLOT(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_pdje_POLYGLOT(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static pdje_POLYGLOTPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_FXControlPannel")]
  public static extern global::System.IntPtr new_FXControlPannel(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_FXControlPannel_GetArgSetter")]
  public static extern global::System.IntPtr FXControlPannel_GetArgSetter(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_FXControlPannel_FX_ON_OFF")]
  public static extern void FXControlPannel_FX_ON_OFF(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_FXControlPannel_addFX")]
  public static extern void FXControlPannel_addFX(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_FXControlPannel_checkSomethingOn")]
  public static extern bool FXControlPannel_checkSomethingOn(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_FXControlPannel")]
  public static extern void delete_FXControlPannel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_toFaustStylePCM")]
  public static extern void toFaustStylePCM(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_toLRStylePCM")]
  public static extern void toLRStylePCM(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_DBROOT_set")]
  public static extern void PDJE_DBROOT_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_DBROOT_get")]
  public static extern global::System.IntPtr PDJE_DBROOT_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_PDJE")]
  public static extern global::System.IntPtr new_PDJE(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_PDJE")]
  public static extern void delete_PDJE(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_player_set")]
  public static extern void PDJE_player_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_player_get")]
  public static extern global::System.IntPtr PDJE_player_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_editor_set")]
  public static extern void PDJE_editor_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_editor_get")]
  public static extern global::System.IntPtr PDJE_editor_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_InitPlayer")]
  public static extern bool PDJE_InitPlayer(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, uint jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_ResetPlayer")]
  public static extern void PDJE_ResetPlayer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_CloseEditor")]
  public static extern void PDJE_CloseEditor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_PullOutDataLine")]
  public static extern global::System.IntPtr PDJE_PullOutDataLine(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_InitEditor")]
  public static extern bool PDJE_InitEditor(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_GetNoteObjects")]
  public static extern bool PDJE_GetNoteObjects(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_SearchMusic__SWIG_0")]
  public static extern global::System.IntPtr PDJE_SearchMusic__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_SearchMusic__SWIG_1")]
  public static extern global::System.IntPtr PDJE_SearchMusic__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_SearchTrack")]
  public static extern global::System.IntPtr PDJE_SearchTrack(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_GetPlayerObject")]
  public static extern global::System.IntPtr PDJE_GetPlayerObject(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_GetEditorObject")]
  public static extern global::System.IntPtr PDJE_GetEditorObject(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_ARGSETTER_WRAPPER")]
  public static extern global::System.IntPtr new_ARGSETTER_WRAPPER(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_ARGSETTER_WRAPPER")]
  public static extern void delete_ARGSETTER_WRAPPER(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_ARGSETTER_WRAPPER_GetFXArgKeys")]
  public static extern global::System.IntPtr ARGSETTER_WRAPPER_GetFXArgKeys(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_ARGSETTER_WRAPPER_SetFXArg")]
  public static extern void ARGSETTER_WRAPPER_SetFXArg(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_litedb_KVGet")]
  public static extern bool litedb_KVGet(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_litedb_KVPut")]
  public static extern bool litedb_KVPut(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_litedb_openDB")]
  public static extern bool litedb_openDB(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_litedb_getRoot")]
  public static extern global::System.IntPtr litedb_getRoot(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_litedb")]
  public static extern global::System.IntPtr new_litedb();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_litedb")]
  public static extern void delete_litedb(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_title_set")]
  public static extern void musdata_title_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_title_get")]
  public static extern string musdata_title_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_composer_set")]
  public static extern void musdata_composer_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_composer_get")]
  public static extern string musdata_composer_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_musicPath_set")]
  public static extern void musdata_musicPath_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_musicPath_get")]
  public static extern string musdata_musicPath_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_bpmBinary_set")]
  public static extern void musdata_bpmBinary_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_bpmBinary_get")]
  public static extern global::System.IntPtr musdata_bpmBinary_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_bpm_set")]
  public static extern void musdata_bpm_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_bpm_get")]
  public static extern double musdata_bpm_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_firstBeat_set")]
  public static extern void musdata_firstBeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_firstBeat_get")]
  public static extern string musdata_firstBeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_musdata__SWIG_0")]
  public static extern global::System.IntPtr new_musdata__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_musdata__SWIG_1")]
  public static extern global::System.IntPtr new_musdata__SWIG_1(string jarg1, string jarg2, string jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_musdata__SWIG_2")]
  public static extern global::System.IntPtr new_musdata__SWIG_2(string jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_musdata__SWIG_3")]
  public static extern global::System.IntPtr new_musdata__SWIG_3(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_musdata__SWIG_4")]
  public static extern global::System.IntPtr new_musdata__SWIG_4(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_musdata__SWIG_5")]
  public static extern global::System.IntPtr new_musdata__SWIG_5();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_GenSearchSTMT")]
  public static extern bool musdata_GenSearchSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_GenInsertSTMT")]
  public static extern bool musdata_GenInsertSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_GenEditSTMT")]
  public static extern bool musdata_GenEditSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_musdata_GenDeleteSTMT")]
  public static extern bool musdata_GenDeleteSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_musdata")]
  public static extern void delete_musdata(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_trackTitle_set")]
  public static extern void trackdata_trackTitle_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_trackTitle_get")]
  public static extern string trackdata_trackTitle_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_mixBinary_set")]
  public static extern void trackdata_mixBinary_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_mixBinary_get")]
  public static extern global::System.IntPtr trackdata_mixBinary_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_noteBinary_set")]
  public static extern void trackdata_noteBinary_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_noteBinary_get")]
  public static extern global::System.IntPtr trackdata_noteBinary_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_cachedMixList_set")]
  public static extern void trackdata_cachedMixList_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_cachedMixList_get")]
  public static extern string trackdata_cachedMixList_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_trackdata__SWIG_0")]
  public static extern global::System.IntPtr new_trackdata__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_trackdata__SWIG_1")]
  public static extern global::System.IntPtr new_trackdata__SWIG_1(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_trackdata__SWIG_2")]
  public static extern global::System.IntPtr new_trackdata__SWIG_2();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_GenSearchSTMT")]
  public static extern bool trackdata_GenSearchSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_GenInsertSTMT")]
  public static extern bool trackdata_GenInsertSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_GenEditSTMT")]
  public static extern bool trackdata_GenEditSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_trackdata_GenDeleteSTMT")]
  public static extern bool trackdata_GenDeleteSTMT(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_trackdata")]
  public static extern void delete_trackdata(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_STATUS_set")]
  public static extern void audioPlayer_STATUS_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_STATUS_get")]
  public static extern string audioPlayer_STATUS_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_GetStatus")]
  public static extern string audioPlayer_GetStatus(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_Activate")]
  public static extern bool audioPlayer_Activate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_Deactivate")]
  public static extern bool audioPlayer_Deactivate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_ChangeCursorPos")]
  public static extern void audioPlayer_ChangeCursorPos(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_GetConsumedFrames")]
  public static extern ulong audioPlayer_GetConsumedFrames(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_GetFXControlPannel__SWIG_0")]
  public static extern global::System.IntPtr audioPlayer_GetFXControlPannel__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_GetFXControlPannel__SWIG_1")]
  public static extern global::System.IntPtr audioPlayer_GetFXControlPannel__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_GetMusicControlPannel")]
  public static extern global::System.IntPtr audioPlayer_GetMusicControlPannel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_audioPlayer__SWIG_0")]
  public static extern global::System.IntPtr new_audioPlayer__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_audioPlayer__SWIG_1")]
  public static extern global::System.IntPtr new_audioPlayer__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_audioPlayer__SWIG_2")]
  public static extern global::System.IntPtr new_audioPlayer__SWIG_2(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioPlayer_PullOutDataLine")]
  public static extern global::System.IntPtr audioPlayer_PullOutDataLine(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_audioPlayer")]
  public static extern void delete_audioPlayer(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_Name_Sanitizer_sanitizeFileName")]
  public static extern global::System.IntPtr PDJE_Name_Sanitizer_sanitizeFileName(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_PDJE_Name_Sanitizer_getFileName")]
  public static extern string PDJE_Name_Sanitizer_getFileName(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_play_set")]
  public static extern void MusicOnDeck_play_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_play_get")]
  public static extern bool MusicOnDeck_play_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_dec_set")]
  public static extern void MusicOnDeck_dec_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_dec_get")]
  public static extern global::System.IntPtr MusicOnDeck_dec_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_fxP_set")]
  public static extern void MusicOnDeck_fxP_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_fxP_get")]
  public static extern global::System.IntPtr MusicOnDeck_fxP_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_st_set")]
  public static extern void MusicOnDeck_st_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicOnDeck_st_get")]
  public static extern global::System.IntPtr MusicOnDeck_st_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MusicOnDeck")]
  public static extern global::System.IntPtr new_MusicOnDeck();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_MusicOnDeck")]
  public static extern void delete_MusicOnDeck(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_LoadMusic")]
  public static extern bool MusicControlPannel_LoadMusic(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_CueMusic")]
  public static extern bool MusicControlPannel_CueMusic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, ulong jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_SetMusic")]
  public static extern bool MusicControlPannel_SetMusic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, bool jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_GetLoadedMusicList")]
  public static extern global::System.IntPtr MusicControlPannel_GetLoadedMusicList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_UnloadMusic")]
  public static extern bool MusicControlPannel_UnloadMusic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_GetPCMFrames")]
  public static extern bool MusicControlPannel_GetPCMFrames(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_getFXHandle")]
  public static extern global::System.IntPtr MusicControlPannel_getFXHandle(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicControlPannel_ChangeBpm")]
  public static extern bool MusicControlPannel_ChangeBpm(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, double jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MusicControlPannel")]
  public static extern global::System.IntPtr new_MusicControlPannel(uint jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_MusicControlPannel")]
  public static extern void delete_MusicControlPannel(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MUSIC_musicName_set")]
  public static extern void EDIT_ARG_MUSIC_musicName_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MUSIC_musicName_get")]
  public static extern string EDIT_ARG_MUSIC_musicName_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MUSIC_arg_set")]
  public static extern void EDIT_ARG_MUSIC_arg_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MUSIC_arg_get")]
  public static extern global::System.IntPtr EDIT_ARG_MUSIC_arg_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_EDIT_ARG_MUSIC")]
  public static extern global::System.IntPtr new_EDIT_ARG_MUSIC();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_EDIT_ARG_MUSIC")]
  public static extern void delete_EDIT_ARG_MUSIC(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_getMixRepo")]
  public static extern global::System.IntPtr editorObject_getMixRepo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_getMusicRepo")]
  public static extern global::System.IntPtr editorObject_getMusicRepo(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_getNoteRepo")]
  public static extern global::System.IntPtr editorObject_getNoteRepo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_getKVRepo")]
  public static extern global::System.IntPtr editorObject_getKVRepo(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_AddLine")]
  public static extern bool editorObject_AddLine(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_deleteLine")]
  public static extern int editorObject_deleteLine(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, bool jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_render")]
  public static extern bool editorObject_render(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_demoPlayInit")]
  public static extern void editorObject_demoPlayInit(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_pushToRootDB__SWIG_0")]
  public static extern bool editorObject_pushToRootDB__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_pushToRootDB__SWIG_1")]
  public static extern bool editorObject_pushToRootDB__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_DESTROY_PROJECT")]
  public static extern string editorObject_DESTROY_PROJECT(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_ConfigNewMusic__SWIG_0")]
  public static extern bool editorObject_ConfigNewMusic__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_ConfigNewMusic__SWIG_1")]
  public static extern bool editorObject_ConfigNewMusic__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_Open")]
  public static extern bool editorObject_Open(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_editorObject")]
  public static extern global::System.IntPtr new_editorObject(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_editorObject")]
  public static extern void delete_editorObject(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_AddLineNote")]
  public static extern bool editorObject_AddLineNote(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_AddLineMix")]
  public static extern bool editorObject_AddLineMix(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_AddLineKV")]
  public static extern bool editorObject_AddLineKV(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_AddLineMusic")]
  public static extern bool editorObject_AddLineMusic(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_deleteLineNote")]
  public static extern int editorObject_deleteLineNote(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_deleteLineKV")]
  public static extern int editorObject_deleteLineKV(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_deleteLineMusic")]
  public static extern int editorObject_deleteLineMusic(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetAllNotes")]
  public static extern void editorObject_GetAllNotes(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetAllMixes")]
  public static extern void editorObject_GetAllMixes(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetAllKeyValues")]
  public static extern void editorObject_GetAllKeyValues(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetAllMusics")]
  public static extern void editorObject_GetAllMusics(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UndoNote")]
  public static extern bool editorObject_UndoNote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UndoMix")]
  public static extern bool editorObject_UndoMix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UndoKV")]
  public static extern bool editorObject_UndoKV(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UndoMusic")]
  public static extern bool editorObject_UndoMusic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_RedoNote")]
  public static extern bool editorObject_RedoNote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_RedoMix")]
  public static extern bool editorObject_RedoMix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_RedoKV")]
  public static extern bool editorObject_RedoKV(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_RedoMusic")]
  public static extern bool editorObject_RedoMusic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GoNote")]
  public static extern bool editorObject_GoNote(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GoMix")]
  public static extern bool editorObject_GoMix(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GoKV")]
  public static extern bool editorObject_GoKV(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GoMusic")]
  public static extern bool editorObject_GoMusic(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetLogNoteJSON")]
  public static extern string editorObject_GetLogNoteJSON(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetLogMixJSON")]
  public static extern string editorObject_GetLogMixJSON(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetLogKVJSON")]
  public static extern string editorObject_GetLogKVJSON(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetLogMusicJSON")]
  public static extern string editorObject_GetLogMusicJSON(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetDiffNote")]
  public static extern global::System.IntPtr editorObject_GetDiffNote(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetDiffMix")]
  public static extern global::System.IntPtr editorObject_GetDiffMix(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetDiffKV")]
  public static extern global::System.IntPtr editorObject_GetDiffKV(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_GetDiffMusic")]
  public static extern global::System.IntPtr editorObject_GetDiffMusic(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogNote")]
  public static extern bool editorObject_UpdateLogNote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogMix")]
  public static extern bool editorObject_UpdateLogMix(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogKV")]
  public static extern bool editorObject_UpdateLogKV(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogMusic")]
  public static extern bool editorObject_UpdateLogMusic(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogNoteOn")]
  public static extern bool editorObject_UpdateLogNoteOn(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogMixOn")]
  public static extern bool editorObject_UpdateLogMixOn(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogKVOn")]
  public static extern bool editorObject_UpdateLogKVOn(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_editorObject_UpdateLogMusicOn")]
  public static extern bool editorObject_UpdateLogMusicOn(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commit_commitPointer_set")]
  public static extern void commit_commitPointer_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commit_commitPointer_get")]
  public static extern global::System.IntPtr commit_commitPointer_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commit_commitID_set")]
  public static extern void commit_commitID_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commit_commitID_get")]
  public static extern global::System.IntPtr commit_commitID_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commit_msg_set")]
  public static extern void commit_msg_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commit_msg_get")]
  public static extern string commit_msg_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_commit__SWIG_0")]
  public static extern global::System.IntPtr new_commit__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_commit__SWIG_1")]
  public static extern global::System.IntPtr new_commit__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_commit__SWIG_2")]
  public static extern global::System.IntPtr new_commit__SWIG_2(string jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_commit")]
  public static extern void delete_commit(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commitList_clist_set")]
  public static extern void commitList_clist_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commitList_clist_get")]
  public static extern global::System.IntPtr commitList_clist_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commitList_Reset")]
  public static extern void commitList_Reset(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commitList_UpdateCommits")]
  public static extern bool commitList_UpdateCommits(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_commitList_OkToAdd")]
  public static extern bool commitList_OkToAdd(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_commitList")]
  public static extern global::System.IntPtr new_commitList();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_commitList")]
  public static extern void delete_commitList(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioRender_rendered_frames_set")]
  public static extern void audioRender_rendered_frames_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioRender_rendered_frames_get")]
  public static extern global::System.IntPtr audioRender_rendered_frames_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioRender_LoadTrack")]
  public static extern bool audioRender_LoadTrack(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_audioRender_LoadTrackFromMixData")]
  public static extern bool audioRender_LoadTrackFromMixData(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_audioRender")]
  public static extern global::System.IntPtr new_audioRender();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_audioRender")]
  public static extern void delete_audioRender(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_EDIT_ARG_KEY_VALUE__SWIG_0")]
  public static extern global::System.IntPtr new_EDIT_ARG_KEY_VALUE__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_EDIT_ARG_KEY_VALUE__SWIG_1")]
  public static extern global::System.IntPtr new_EDIT_ARG_KEY_VALUE__SWIG_1(string jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_EDIT_ARG_KEY_VALUE__SWIG_2")]
  public static extern global::System.IntPtr new_EDIT_ARG_KEY_VALUE__SWIG_2(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_KEY_VALUE_first_set")]
  public static extern void EDIT_ARG_KEY_VALUE_first_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_KEY_VALUE_first_get")]
  public static extern string EDIT_ARG_KEY_VALUE_first_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_KEY_VALUE_second_set")]
  public static extern void EDIT_ARG_KEY_VALUE_second_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_KEY_VALUE_second_get")]
  public static extern string EDIT_ARG_KEY_VALUE_second_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_EDIT_ARG_KEY_VALUE")]
  public static extern void delete_EDIT_ARG_KEY_VALUE(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_type_set")]
  public static extern void EDIT_ARG_MIX_type_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_type_get")]
  public static extern int EDIT_ARG_MIX_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_details_set")]
  public static extern void EDIT_ARG_MIX_details_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_details_get")]
  public static extern int EDIT_ARG_MIX_details_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_ID_set")]
  public static extern void EDIT_ARG_MIX_ID_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_ID_get")]
  public static extern int EDIT_ARG_MIX_ID_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_first_set")]
  public static extern void EDIT_ARG_MIX_first_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_first_get")]
  public static extern string EDIT_ARG_MIX_first_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_second_set")]
  public static extern void EDIT_ARG_MIX_second_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_second_get")]
  public static extern string EDIT_ARG_MIX_second_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_third_set")]
  public static extern void EDIT_ARG_MIX_third_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_third_get")]
  public static extern string EDIT_ARG_MIX_third_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_beat_set")]
  public static extern void EDIT_ARG_MIX_beat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_beat_get")]
  public static extern long EDIT_ARG_MIX_beat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_subBeat_set")]
  public static extern void EDIT_ARG_MIX_subBeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_subBeat_get")]
  public static extern long EDIT_ARG_MIX_subBeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_separate_set")]
  public static extern void EDIT_ARG_MIX_separate_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_separate_get")]
  public static extern long EDIT_ARG_MIX_separate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_Ebeat_set")]
  public static extern void EDIT_ARG_MIX_Ebeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_Ebeat_get")]
  public static extern long EDIT_ARG_MIX_Ebeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_EsubBeat_set")]
  public static extern void EDIT_ARG_MIX_EsubBeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_EsubBeat_get")]
  public static extern long EDIT_ARG_MIX_EsubBeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_Eseparate_set")]
  public static extern void EDIT_ARG_MIX_Eseparate_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_MIX_Eseparate_get")]
  public static extern long EDIT_ARG_MIX_Eseparate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_EDIT_ARG_MIX")]
  public static extern global::System.IntPtr new_EDIT_ARG_MIX();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_EDIT_ARG_MIX")]
  public static extern void delete_EDIT_ARG_MIX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Note_Type_set")]
  public static extern void EDIT_ARG_NOTE_Note_Type_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Note_Type_get")]
  public static extern string EDIT_ARG_NOTE_Note_Type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Note_Detail_set")]
  public static extern void EDIT_ARG_NOTE_Note_Detail_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Note_Detail_get")]
  public static extern string EDIT_ARG_NOTE_Note_Detail_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_first_set")]
  public static extern void EDIT_ARG_NOTE_first_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_first_get")]
  public static extern string EDIT_ARG_NOTE_first_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_second_set")]
  public static extern void EDIT_ARG_NOTE_second_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_second_get")]
  public static extern string EDIT_ARG_NOTE_second_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_third_set")]
  public static extern void EDIT_ARG_NOTE_third_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_third_get")]
  public static extern string EDIT_ARG_NOTE_third_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_beat_set")]
  public static extern void EDIT_ARG_NOTE_beat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_beat_get")]
  public static extern long EDIT_ARG_NOTE_beat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_subBeat_set")]
  public static extern void EDIT_ARG_NOTE_subBeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_subBeat_get")]
  public static extern long EDIT_ARG_NOTE_subBeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_separate_set")]
  public static extern void EDIT_ARG_NOTE_separate_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_separate_get")]
  public static extern long EDIT_ARG_NOTE_separate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Ebeat_set")]
  public static extern void EDIT_ARG_NOTE_Ebeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Ebeat_get")]
  public static extern long EDIT_ARG_NOTE_Ebeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_EsubBeat_set")]
  public static extern void EDIT_ARG_NOTE_EsubBeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_EsubBeat_get")]
  public static extern long EDIT_ARG_NOTE_EsubBeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Eseparate_set")]
  public static extern void EDIT_ARG_NOTE_Eseparate_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_EDIT_ARG_NOTE_Eseparate_get")]
  public static extern long EDIT_ARG_NOTE_Eseparate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_EDIT_ARG_NOTE")]
  public static extern global::System.IntPtr new_EDIT_ARG_NOTE();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_EDIT_ARG_NOTE")]
  public static extern void delete_EDIT_ARG_NOTE(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_bpm_set")]
  public static extern void MusicArgs_bpm_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_bpm_get")]
  public static extern string MusicArgs_bpm_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_beat_set")]
  public static extern void MusicArgs_beat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_beat_get")]
  public static extern long MusicArgs_beat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_subBeat_set")]
  public static extern void MusicArgs_subBeat_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_subBeat_get")]
  public static extern long MusicArgs_subBeat_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_separate_set")]
  public static extern void MusicArgs_separate_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicArgs_separate_get")]
  public static extern long MusicArgs_separate_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MusicArgs")]
  public static extern global::System.IntPtr new_MusicArgs();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_MusicArgs")]
  public static extern void delete_MusicArgs(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_NoteVisitor")]
  public static extern void delete_NoteVisitor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_NoteVisitor_on_item")]
  public static extern void NoteVisitor_on_item(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_NoteVisitor")]
  public static extern global::System.IntPtr new_NoteVisitor();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_NoteVisitor_director_connect")]
  public static extern void NoteVisitor_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, NoteVisitor.SwigDelegateNoteVisitor_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_MixVisitor")]
  public static extern void delete_MixVisitor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MixVisitor_on_item")]
  public static extern void MixVisitor_on_item(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MixVisitor")]
  public static extern global::System.IntPtr new_MixVisitor();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MixVisitor_director_connect")]
  public static extern void MixVisitor_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, MixVisitor.SwigDelegateMixVisitor_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_KVVisitor")]
  public static extern void delete_KVVisitor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KVVisitor_on_item")]
  public static extern void KVVisitor_on_item(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_KVVisitor")]
  public static extern global::System.IntPtr new_KVVisitor();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KVVisitor_director_connect")]
  public static extern void KVVisitor_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, KVVisitor.SwigDelegateKVVisitor_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_MusicVisitor")]
  public static extern void delete_MusicVisitor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicVisitor_on_item")]
  public static extern void MusicVisitor_on_item(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MusicVisitor")]
  public static extern global::System.IntPtr new_MusicVisitor();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MusicVisitor_director_connect")]
  public static extern void MusicVisitor_director_connect(global::System.Runtime.InteropServices.HandleRef jarg1, MusicVisitor.SwigDelegateMusicVisitor_0 delegate0);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_Clear")]
  public static extern void MUS_VEC_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_Add")]
  public static extern void MUS_VEC_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_size")]
  public static extern uint MUS_VEC_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_capacity")]
  public static extern uint MUS_VEC_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_reserve")]
  public static extern void MUS_VEC_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MUS_VEC__SWIG_0")]
  public static extern global::System.IntPtr new_MUS_VEC__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MUS_VEC__SWIG_1")]
  public static extern global::System.IntPtr new_MUS_VEC__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_MUS_VEC__SWIG_2")]
  public static extern global::System.IntPtr new_MUS_VEC__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_getitemcopy")]
  public static extern global::System.IntPtr MUS_VEC_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_getitem")]
  public static extern global::System.IntPtr MUS_VEC_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_setitem")]
  public static extern void MUS_VEC_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_AddRange")]
  public static extern void MUS_VEC_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_GetRange")]
  public static extern global::System.IntPtr MUS_VEC_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_Insert")]
  public static extern void MUS_VEC_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_InsertRange")]
  public static extern void MUS_VEC_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_RemoveAt")]
  public static extern void MUS_VEC_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_RemoveRange")]
  public static extern void MUS_VEC_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_Repeat")]
  public static extern global::System.IntPtr MUS_VEC_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_Reverse__SWIG_0")]
  public static extern void MUS_VEC_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_Reverse__SWIG_1")]
  public static extern void MUS_VEC_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_MUS_VEC_SetRange")]
  public static extern void MUS_VEC_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_MUS_VEC")]
  public static extern void delete_MUS_VEC(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_Clear")]
  public static extern void TRACK_VEC_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_Add")]
  public static extern void TRACK_VEC_Add(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_size")]
  public static extern uint TRACK_VEC_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_capacity")]
  public static extern uint TRACK_VEC_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_reserve")]
  public static extern void TRACK_VEC_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_TRACK_VEC__SWIG_0")]
  public static extern global::System.IntPtr new_TRACK_VEC__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_TRACK_VEC__SWIG_1")]
  public static extern global::System.IntPtr new_TRACK_VEC__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_TRACK_VEC__SWIG_2")]
  public static extern global::System.IntPtr new_TRACK_VEC__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_getitemcopy")]
  public static extern global::System.IntPtr TRACK_VEC_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_getitem")]
  public static extern global::System.IntPtr TRACK_VEC_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_setitem")]
  public static extern void TRACK_VEC_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_AddRange")]
  public static extern void TRACK_VEC_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_GetRange")]
  public static extern global::System.IntPtr TRACK_VEC_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_Insert")]
  public static extern void TRACK_VEC_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_InsertRange")]
  public static extern void TRACK_VEC_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_RemoveAt")]
  public static extern void TRACK_VEC_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_RemoveRange")]
  public static extern void TRACK_VEC_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_Repeat")]
  public static extern global::System.IntPtr TRACK_VEC_Repeat(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_Reverse__SWIG_0")]
  public static extern void TRACK_VEC_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_Reverse__SWIG_1")]
  public static extern void TRACK_VEC_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_TRACK_VEC_SetRange")]
  public static extern void TRACK_VEC_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_TRACK_VEC")]
  public static extern void delete_TRACK_VEC(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Clear")]
  public static extern void KEY_VEC_Clear(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Add")]
  public static extern void KEY_VEC_Add(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_size")]
  public static extern uint KEY_VEC_size(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_capacity")]
  public static extern uint KEY_VEC_capacity(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_reserve")]
  public static extern void KEY_VEC_reserve(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_KEY_VEC__SWIG_0")]
  public static extern global::System.IntPtr new_KEY_VEC__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_KEY_VEC__SWIG_1")]
  public static extern global::System.IntPtr new_KEY_VEC__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_new_KEY_VEC__SWIG_2")]
  public static extern global::System.IntPtr new_KEY_VEC__SWIG_2(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_getitemcopy")]
  public static extern string KEY_VEC_getitemcopy(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_getitem")]
  public static extern string KEY_VEC_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_setitem")]
  public static extern void KEY_VEC_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_AddRange")]
  public static extern void KEY_VEC_AddRange(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_GetRange")]
  public static extern global::System.IntPtr KEY_VEC_GetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Insert")]
  public static extern void KEY_VEC_Insert(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_InsertRange")]
  public static extern void KEY_VEC_InsertRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_RemoveAt")]
  public static extern void KEY_VEC_RemoveAt(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_RemoveRange")]
  public static extern void KEY_VEC_RemoveRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Repeat")]
  public static extern global::System.IntPtr KEY_VEC_Repeat(string jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Reverse__SWIG_0")]
  public static extern void KEY_VEC_Reverse__SWIG_0(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Reverse__SWIG_1")]
  public static extern void KEY_VEC_Reverse__SWIG_1(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_SetRange")]
  public static extern void KEY_VEC_SetRange(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Contains")]
  public static extern bool KEY_VEC_Contains(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_IndexOf")]
  public static extern int KEY_VEC_IndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_LastIndexOf")]
  public static extern int KEY_VEC_LastIndexOf(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_KEY_VEC_Remove")]
  public static extern bool KEY_VEC_Remove(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("libpdje_csharp", EntryPoint="CSharp_delete_KEY_VEC")]
  public static extern void delete_KEY_VEC(global::System.Runtime.InteropServices.HandleRef jarg1);
}
