//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.4.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class trackdata : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal trackdata(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(trackdata obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(trackdata obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~trackdata() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          pdje_POLYGLOTPINVOKE.delete_trackdata(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string trackTitle {
    set {
      pdje_POLYGLOTPINVOKE.trackdata_trackTitle_set(swigCPtr, value);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pdje_POLYGLOTPINVOKE.trackdata_trackTitle_get(swigCPtr);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_BIN mixBinary {
    set {
      pdje_POLYGLOTPINVOKE.trackdata_mixBinary_set(swigCPtr, SWIGTYPE_p_BIN.getCPtr(value));
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_BIN ret = new SWIGTYPE_p_BIN(pdje_POLYGLOTPINVOKE.trackdata_mixBinary_get(swigCPtr), true);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public SWIGTYPE_p_BIN noteBinary {
    set {
      pdje_POLYGLOTPINVOKE.trackdata_noteBinary_set(swigCPtr, SWIGTYPE_p_BIN.getCPtr(value));
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_BIN ret = new SWIGTYPE_p_BIN(pdje_POLYGLOTPINVOKE.trackdata_noteBinary_get(swigCPtr), true);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string cachedMixList {
    set {
      pdje_POLYGLOTPINVOKE.trackdata_cachedMixList_set(swigCPtr, value);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = pdje_POLYGLOTPINVOKE.trackdata_cachedMixList_get(swigCPtr);
      if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public trackdata(SWIGTYPE_p_stmt dbstate) : this(pdje_POLYGLOTPINVOKE.new_trackdata__SWIG_0(SWIGTYPE_p_stmt.getCPtr(dbstate)), true) {
  }

  public trackdata(string trackTitle__) : this(pdje_POLYGLOTPINVOKE.new_trackdata__SWIG_1(trackTitle__), true) {
    if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
  }

  public trackdata() : this(pdje_POLYGLOTPINVOKE.new_trackdata__SWIG_2(), true) {
  }

  public bool GenSearchSTMT(SWIGTYPE_p_stmt dbstate, SWIGTYPE_p_sqlite3 db) {
    bool ret = pdje_POLYGLOTPINVOKE.trackdata_GenSearchSTMT(swigCPtr, SWIGTYPE_p_stmt.getCPtr(dbstate), SWIGTYPE_p_sqlite3.getCPtr(db));
    if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GenInsertSTMT(SWIGTYPE_p_stmt dbstate, SWIGTYPE_p_sqlite3 db) {
    bool ret = pdje_POLYGLOTPINVOKE.trackdata_GenInsertSTMT(swigCPtr, SWIGTYPE_p_stmt.getCPtr(dbstate), SWIGTYPE_p_sqlite3.getCPtr(db));
    if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GenEditSTMT(SWIGTYPE_p_stmt dbstate, SWIGTYPE_p_sqlite3 db, trackdata toEdit) {
    bool ret = pdje_POLYGLOTPINVOKE.trackdata_GenEditSTMT(swigCPtr, SWIGTYPE_p_stmt.getCPtr(dbstate), SWIGTYPE_p_sqlite3.getCPtr(db), trackdata.getCPtr(toEdit));
    if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool GenDeleteSTMT(SWIGTYPE_p_stmt dbstate, SWIGTYPE_p_sqlite3 db) {
    bool ret = pdje_POLYGLOTPINVOKE.trackdata_GenDeleteSTMT(swigCPtr, SWIGTYPE_p_stmt.getCPtr(dbstate), SWIGTYPE_p_sqlite3.getCPtr(db));
    if (pdje_POLYGLOTPINVOKE.SWIGPendingException.Pending) throw pdje_POLYGLOTPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
