//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum TypeEnum {
  FILTER,
  EQ,
  DISTORTION,
  CONTROL,
  VOL,
  LOAD,
  UNLOAD,
  BPM_CONTROL,
  ECHO,
  OSC_FILTER,
  FLANGER,
  PHASER,
  TRANCE,
  PANNER,
  BATTLE_DJ,
  ROLL,
  COMPRESSOR,
  ROBOT
}
