/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: /home/rrop/rropdb/box_inside/pdje/Project_DJ_Engine/PDJE_swig.i


extern
#ifdef __cplusplus
  "C"
#endif
  void cgo_panic__pdje_POLYGLOT_e341992d737e46dc(const char*);
static void _swig_gopanic(const char *p) {
  cgo_panic__pdje_POLYGLOT_e341992d737e46dc(p);
}



#define SWIG_VERSION 0x040400
#define SWIGGO
#define SWIGMODULE pdje_POLYGLOT
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif

#if defined(__cplusplus) && __cplusplus >=201103L
# define SWIG_NOEXCEPT noexcept
#else
# define SWIG_NOEXCEPT throw()
#endif 

/* -----------------------------------------------------------------------------
 * swigcompat.swg
 *
 * Macros to provide support compatibility with older C and C++ standards.
 *
 * Note that SWIG expects __cplusplus to be defined to the appropriate C++ standard.
 * MSVC users are urged to check and examine the /Zc:__cplusplus compiler option.
 * See https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus.
 * ----------------------------------------------------------------------------- */

/* C99 and C++11 should provide snprintf, but define SWIG_NO_SNPRINTF
 * if you're missing it.
 */
#if ((defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L) || \
     (defined __cplusplus && __cplusplus >= 201103L) || \
     defined SWIG_HAVE_SNPRINTF) && \
    !defined SWIG_NO_SNPRINTF
# define SWIG_snprintf(O,S,F,A) snprintf(O,S,F,A)
# define SWIG_snprintf2(O,S,F,A,B) snprintf(O,S,F,A,B)
#else
/* Fallback versions ignore the buffer size, but most of our uses either have a
 * fixed maximum possible size or dynamically allocate a buffer that's large
 * enough.
 */
# define SWIG_snprintf(O,S,F,A) sprintf(O,F,A)
# define SWIG_snprintf2(O,S,F,A,B) sprintf(O,F,A,B)
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef ptrdiff_t intgo;
typedef size_t uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;



static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


#ifdef __cplusplus
#include <utility>
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigSmartPointer {
    T *ptr;
    SwigSmartPointer(T *p) : ptr(p) { }
    ~SwigSmartPointer() { delete ptr; }
    SwigSmartPointer& operator=(SwigSmartPointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
    void reset(T *p) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = p; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigSmartPointer tmp(new T(t)); pointer = tmp; return *this; }
#if __cplusplus >=201103L
  SwigValueWrapper& operator=(T&& t) { SwigSmartPointer tmp(new T(std::move(t))); pointer = tmp; return *this; }
  operator T&&() const { return std::move(*pointer.ptr); }
#else
  operator T&() const { return *pointer.ptr; }
#endif
  T *operator&() const { return pointer.ptr; }
  static void reset(SwigValueWrapper& t, T *p) { t.pointer.reset(p); }
};

/*
 * SwigValueInit() is a generic initialisation solution as the following approach:
 * 
 *       T c_result = T();
 * 
 * doesn't compile for all types for example:
 * 
 *       unsigned int c_result = unsigned int();
 */
template <typename T> T SwigValueInit() {
  return T();
}

#if __cplusplus >=201103L
# define SWIG_STD_MOVE(OBJ) std::move(OBJ)
#else
# define SWIG_STD_MOVE(OBJ) OBJ
#endif

#endif


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


    #include <vector>
    #include "PDJE_interface.hpp"
    #include "dbRoot.hpp"
    #include "musicDB.hpp"
    #include "trackDB.hpp"
    #include <string>
    #include "ManualMix.hpp"
    #include "audioPlayer.hpp"
    #include "fileNameSanitizer.hpp"
    #include "editorObject.hpp"
    #include "PDJE_EXPORT_SETTER.hpp"
    #include "rocksdb/rocksdb_namespace.h"
    #include <filesystem>
    #include "rocksdb/db.h"
    // #include <rocksdb/options.h>
    // #include <rocksdb/table.h>
    // #include <rocksdb/filter_policy.h>


#include <vector>
#include <stdexcept>


#include <string>

SWIGINTERN std::vector< musdata >::const_reference std_vector_Sl_musdata_Sg__get(std::vector< musdata > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_musdata_Sg__set(std::vector< musdata > *self,int i,std::vector< musdata >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< trackdata >::const_reference std_vector_Sl_trackdata_Sg__get(std::vector< trackdata > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_trackdata_Sg__set(std::vector< trackdata > *self,int i,std::vector< trackdata >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN std::vector< std::string >::const_reference std_vector_Sl_std_string_Sg__get(std::vector< std::string > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_std_string_Sg__set(std::vector< std::string > *self,int i,std::vector< std::string >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_pdje_POLYGLOT_e341992d737e46dc(void *_swig_go_0) {
  void *arg1 = 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_pdje_POLYGLOT_e341992d737e46dc(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


intgo _wrap_COMPRESSOR_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = COMPRESSOR;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_DISTORTION_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = DISTORTION;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ECHO_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = ECHO;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_EQ_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = EQ;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_FILTER_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = FILTER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_FLANGER_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = FLANGER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_OCSFILTER_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = OCSFILTER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_PANNER_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = PANNER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_PHASER_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = PHASER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ROBOT_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = ROBOT;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_ROLL_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = ROLL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_TRANCE_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = TRANCE;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_VOL_pdje_POLYGLOT_e341992d737e46dc() {
  FXList result;
  intgo _swig_go_result;
  
  
  result = VOL;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_FXControlPannel_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  FXControlPannel = arg1;
  
}


PDJE_API *_wrap_FXControlPannel_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = FXControlPannel;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


void _wrap_toFaustStylePCM_pdje_POLYGLOT_e341992d737e46dc(float **_swig_go_0, float *_swig_go_1, long long _swig_go_2) {
  float **arg1 = 0 ;
  float *arg2 = 0 ;
  unsigned long arg3 ;
  
  arg1 = *(float ***)&_swig_go_0; 
  arg2 = *(float **)&_swig_go_1; 
  arg3 = (unsigned long)_swig_go_2; 
  
  toFaustStylePCM(arg1,arg2,arg3);
  
}


void _wrap_toLRStylePCM_pdje_POLYGLOT_e341992d737e46dc(float **_swig_go_0, float *_swig_go_1, long long _swig_go_2) {
  float **arg1 = 0 ;
  float *arg2 = 0 ;
  unsigned long arg3 ;
  
  arg1 = *(float ***)&_swig_go_0; 
  arg2 = *(float **)&_swig_go_1; 
  arg3 = (unsigned long)_swig_go_2; 
  
  toLRStylePCM(arg1,arg2,arg3);
  
}


intgo _wrap_FULL_PRE_RENDER_pdje_POLYGLOT_e341992d737e46dc() {
  PLAY_MODE result;
  intgo _swig_go_result;
  
  
  result = FULL_PRE_RENDER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_HYBRID_RENDER_pdje_POLYGLOT_e341992d737e46dc() {
  PLAY_MODE result;
  intgo _swig_go_result;
  
  
  result = HYBRID_RENDER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


intgo _wrap_FULL_MANUAL_RENDER_pdje_POLYGLOT_e341992d737e46dc() {
  PLAY_MODE result;
  intgo _swig_go_result;
  
  
  result = FULL_MANUAL_RENDER;
  
  _swig_go_result = (intgo)result; 
  return _swig_go_result;
}


void _wrap_PDJE_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  PDJE = arg1;
  
}


PDJE_API *_wrap_PDJE_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = PDJE;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


void _wrap_ARGSETTER_WRAPPER_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  ARGSETTER_WRAPPER = arg1;
  
}


PDJE_API *_wrap_ARGSETTER_WRAPPER_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = ARGSETTER_WRAPPER;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


void _wrap_litedb_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  litedb = arg1;
  
}


PDJE_API *_wrap_litedb_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = litedb;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


void _wrap_musdata_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  musdata = arg1;
  
}


PDJE_API *_wrap_musdata_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = musdata;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


void _wrap_trackdata_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  trackdata = arg1;
  
}


PDJE_API *_wrap_trackdata_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = trackdata;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


void _wrap_audioPlayer_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  audioPlayer = arg1;
  
}


PDJE_API *_wrap_audioPlayer_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = audioPlayer;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


std::optional< std::string > *_wrap_PDJE_Name_Sanitizer_sanitizeFileName_pdje_POLYGLOT_e341992d737e46dc(_gostring_ _swig_go_0) {
  std::string *arg1 = 0 ;
  SwigValueWrapper< std::optional< std::string > > result;
  std::optional< std::string > *_swig_go_result;
  
  
  std::string arg1_str(_swig_go_0.p, _swig_go_0.n);
  arg1 = &arg1_str;
  
  
  result = PDJE_Name_Sanitizer::sanitizeFileName((std::string const &)*arg1);
  *(std::optional< SANITIZED > **)&_swig_go_result = new std::optional< SANITIZED >(result); 
  return _swig_go_result;
}


_gostring_ _wrap_PDJE_Name_Sanitizer_getFileName_pdje_POLYGLOT_e341992d737e46dc(_gostring_ _swig_go_0) {
  SANITIZED *arg1 = 0 ;
  std::string result;
  _gostring_ _swig_go_result;
  
  
  SANITIZED arg1_str(_swig_go_0.p, _swig_go_0.n);
  arg1 = &arg1_str;
  
  
  result = PDJE_Name_Sanitizer::getFileName((std::string const &)*arg1);
  _swig_go_result = Swig_AllocateString((&result)->data(), (&result)->length()); 
  return _swig_go_result;
}


void _wrap_PDJE_Name_Sanitizer_PDJE_SANITIZE_ERROR_set_pdje_POLYGLOT_e341992d737e46dc(_gostring_ _swig_go_0) {
  std::string *arg1 = 0 ;
  
  
  std::string arg1_str(_swig_go_0.p, _swig_go_0.n);
  arg1 = &arg1_str;
  
  
  PDJE_Name_Sanitizer::PDJE_SANITIZE_ERROR = *arg1;
  
}


_gostring_ _wrap_PDJE_Name_Sanitizer_PDJE_SANITIZE_ERROR_get_pdje_POLYGLOT_e341992d737e46dc() {
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  
  result = (std::string *) &PDJE_Name_Sanitizer::PDJE_SANITIZE_ERROR;
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_EDIT_ARG_MUSIC_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  EDIT_ARG_MUSIC = arg1;
  
}


PDJE_API *_wrap_EDIT_ARG_MUSIC_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = EDIT_ARG_MUSIC;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


void _wrap_editorObject_set_pdje_POLYGLOT_e341992d737e46dc(PDJE_API *_swig_go_0) {
  PDJE_API arg1 ;
  PDJE_API *argp1 ;
  
  
  argp1 = (PDJE_API *)_swig_go_0;
  if (argp1 == NULL) {
    _swig_gopanic("Attempt to dereference null PDJE_API");
  }
  arg1 = (PDJE_API)*argp1;
  
  
  editorObject = arg1;
  
}


PDJE_API *_wrap_editorObject_get_pdje_POLYGLOT_e341992d737e46dc() {
  PDJE_API result;
  PDJE_API *_swig_go_result;
  
  
  result = editorObject;
  *(PDJE_API **)&_swig_go_result = new PDJE_API(result); 
  return _swig_go_result;
}


std::vector< musdata > *_wrap_new_MUS_VEC__SWIG_0_pdje_POLYGLOT_e341992d737e46dc() {
  std::vector< musdata > *result = 0 ;
  std::vector< musdata > *_swig_go_result;
  
  
  result = (std::vector< musdata > *)new std::vector< musdata >();
  *(std::vector< musdata > **)&_swig_go_result = (std::vector< musdata > *)result; 
  return _swig_go_result;
}


std::vector< musdata > *_wrap_new_MUS_VEC__SWIG_1_pdje_POLYGLOT_e341992d737e46dc(long long _swig_go_0) {
  std::vector< musdata >::size_type arg1 ;
  std::vector< musdata > *result = 0 ;
  std::vector< musdata > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< musdata > *)new std::vector< musdata >(SWIG_STD_MOVE(arg1));
  *(std::vector< musdata > **)&_swig_go_result = (std::vector< musdata > *)result; 
  return _swig_go_result;
}


std::vector< musdata > *_wrap_new_MUS_VEC__SWIG_2_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0) {
  std::vector< musdata > *arg1 = 0 ;
  std::vector< musdata > *result = 0 ;
  std::vector< musdata > *_swig_go_result;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  
  result = (std::vector< musdata > *)new std::vector< musdata >((std::vector< musdata > const &)*arg1);
  *(std::vector< musdata > **)&_swig_go_result = (std::vector< musdata > *)result; 
  return _swig_go_result;
}


long long _wrap_MUS_VEC_size_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0) {
  std::vector< musdata > *arg1 = 0 ;
  std::vector< musdata >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  
  result = ((std::vector< musdata > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_MUS_VEC_capacity_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0) {
  std::vector< musdata > *arg1 = 0 ;
  std::vector< musdata >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  
  result = ((std::vector< musdata > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_MUS_VEC_reserve_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0, long long _swig_go_1) {
  std::vector< musdata > *arg1 = 0 ;
  std::vector< musdata >::size_type arg2 ;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(SWIG_STD_MOVE(arg2));
  
}


bool _wrap_MUS_VEC_isEmpty_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0) {
  std::vector< musdata > *arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  
  result = (bool)((std::vector< musdata > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_MUS_VEC_clear_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0) {
  std::vector< musdata > *arg1 = 0 ;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_MUS_VEC_add_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0, musdata *_swig_go_1) {
  std::vector< musdata > *arg1 = 0 ;
  std::vector< musdata >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  arg2 = *(std::vector< musdata >::value_type **)&_swig_go_1; 
  
  (arg1)->push_back((std::vector< musdata >::value_type const &)*arg2);
  
}


musdata *_wrap_MUS_VEC_get_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0, intgo _swig_go_1) {
  std::vector< musdata > *arg1 = 0 ;
  int arg2 ;
  std::vector< musdata >::value_type *result = 0 ;
  musdata *_swig_go_result;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< musdata >::value_type *) &std_vector_Sl_musdata_Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  *(std::vector< musdata >::value_type **)&_swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_MUS_VEC_set_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0, intgo _swig_go_1, musdata *_swig_go_2) {
  std::vector< musdata > *arg1 = 0 ;
  int arg2 ;
  std::vector< musdata >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(std::vector< musdata >::value_type **)&_swig_go_2; 
  
  try {
    std_vector_Sl_musdata_Sg__set(arg1,arg2,(musdata const &)*arg3);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  
}


void _wrap_delete_MUS_VEC_pdje_POLYGLOT_e341992d737e46dc(std::vector< musdata > *_swig_go_0) {
  std::vector< musdata > *arg1 = 0 ;
  
  arg1 = *(std::vector< musdata > **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< trackdata > *_wrap_new_TRACK_VEC__SWIG_0_pdje_POLYGLOT_e341992d737e46dc() {
  std::vector< trackdata > *result = 0 ;
  std::vector< trackdata > *_swig_go_result;
  
  
  result = (std::vector< trackdata > *)new std::vector< trackdata >();
  *(std::vector< trackdata > **)&_swig_go_result = (std::vector< trackdata > *)result; 
  return _swig_go_result;
}


std::vector< trackdata > *_wrap_new_TRACK_VEC__SWIG_1_pdje_POLYGLOT_e341992d737e46dc(long long _swig_go_0) {
  std::vector< trackdata >::size_type arg1 ;
  std::vector< trackdata > *result = 0 ;
  std::vector< trackdata > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< trackdata > *)new std::vector< trackdata >(SWIG_STD_MOVE(arg1));
  *(std::vector< trackdata > **)&_swig_go_result = (std::vector< trackdata > *)result; 
  return _swig_go_result;
}


std::vector< trackdata > *_wrap_new_TRACK_VEC__SWIG_2_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0) {
  std::vector< trackdata > *arg1 = 0 ;
  std::vector< trackdata > *result = 0 ;
  std::vector< trackdata > *_swig_go_result;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  
  result = (std::vector< trackdata > *)new std::vector< trackdata >((std::vector< trackdata > const &)*arg1);
  *(std::vector< trackdata > **)&_swig_go_result = (std::vector< trackdata > *)result; 
  return _swig_go_result;
}


long long _wrap_TRACK_VEC_size_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0) {
  std::vector< trackdata > *arg1 = 0 ;
  std::vector< trackdata >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  
  result = ((std::vector< trackdata > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_TRACK_VEC_capacity_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0) {
  std::vector< trackdata > *arg1 = 0 ;
  std::vector< trackdata >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  
  result = ((std::vector< trackdata > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_TRACK_VEC_reserve_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0, long long _swig_go_1) {
  std::vector< trackdata > *arg1 = 0 ;
  std::vector< trackdata >::size_type arg2 ;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(SWIG_STD_MOVE(arg2));
  
}


bool _wrap_TRACK_VEC_isEmpty_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0) {
  std::vector< trackdata > *arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  
  result = (bool)((std::vector< trackdata > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_TRACK_VEC_clear_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0) {
  std::vector< trackdata > *arg1 = 0 ;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_TRACK_VEC_add_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0, trackdata *_swig_go_1) {
  std::vector< trackdata > *arg1 = 0 ;
  std::vector< trackdata >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  arg2 = *(std::vector< trackdata >::value_type **)&_swig_go_1; 
  
  (arg1)->push_back((std::vector< trackdata >::value_type const &)*arg2);
  
}


trackdata *_wrap_TRACK_VEC_get_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0, intgo _swig_go_1) {
  std::vector< trackdata > *arg1 = 0 ;
  int arg2 ;
  std::vector< trackdata >::value_type *result = 0 ;
  trackdata *_swig_go_result;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< trackdata >::value_type *) &std_vector_Sl_trackdata_Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  *(std::vector< trackdata >::value_type **)&_swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_TRACK_VEC_set_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0, intgo _swig_go_1, trackdata *_swig_go_2) {
  std::vector< trackdata > *arg1 = 0 ;
  int arg2 ;
  std::vector< trackdata >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(std::vector< trackdata >::value_type **)&_swig_go_2; 
  
  try {
    std_vector_Sl_trackdata_Sg__set(arg1,arg2,(trackdata const &)*arg3);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  
}


void _wrap_delete_TRACK_VEC_pdje_POLYGLOT_e341992d737e46dc(std::vector< trackdata > *_swig_go_0) {
  std::vector< trackdata > *arg1 = 0 ;
  
  arg1 = *(std::vector< trackdata > **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< std::string > *_wrap_new_KEY_VEC__SWIG_0_pdje_POLYGLOT_e341992d737e46dc() {
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  
  result = (std::vector< std::string > *)new std::vector< std::string >();
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_KEY_VEC__SWIG_1_pdje_POLYGLOT_e341992d737e46dc(long long _swig_go_0) {
  std::vector< std::string >::size_type arg1 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< std::string > *)new std::vector< std::string >(SWIG_STD_MOVE(arg1));
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


std::vector< std::string > *_wrap_new_KEY_VEC__SWIG_2_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string > *result = 0 ;
  std::vector< std::string > *_swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = (std::vector< std::string > *)new std::vector< std::string >((std::vector< std::string > const &)*arg1);
  *(std::vector< std::string > **)&_swig_go_result = (std::vector< std::string > *)result; 
  return _swig_go_result;
}


long long _wrap_KEY_VEC_size_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_KEY_VEC_capacity_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = ((std::vector< std::string > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_KEY_VEC_reserve_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0, long long _swig_go_1) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::size_type arg2 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(SWIG_STD_MOVE(arg2));
  
}


bool _wrap_KEY_VEC_isEmpty_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  result = (bool)((std::vector< std::string > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_KEY_VEC_clear_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_KEY_VEC_add_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0, _gostring_ _swig_go_1) {
  std::vector< std::string > *arg1 = 0 ;
  std::vector< std::string >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  std::vector< std::string >::value_type arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  (arg1)->push_back((std::vector< std::string >::value_type const &)*arg2);
  
}


_gostring_ _wrap_KEY_VEC_get_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0, intgo _swig_go_1) {
  std::vector< std::string > *arg1 = 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< std::string >::value_type *) &std_vector_Sl_std_string_Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_KEY_VEC_set_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0, intgo _swig_go_1, _gostring_ _swig_go_2) {
  std::vector< std::string > *arg1 = 0 ;
  int arg2 ;
  std::vector< std::string >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  std::vector< std::string >::value_type arg3_str(_swig_go_2.p, _swig_go_2.n);
  arg3 = &arg3_str;
  
  
  try {
    std_vector_Sl_std_string_Sg__set(arg1,arg2,(std::string const &)*arg3);
  } catch(std::out_of_range &_e) {
    (void)_e;
    _swig_gopanic("C++ std::out_of_range exception thrown");
    
  }
  
}


void _wrap_delete_KEY_VEC_pdje_POLYGLOT_e341992d737e46dc(std::vector< std::string > *_swig_go_0) {
  std::vector< std::string > *arg1 = 0 ;
  
  arg1 = *(std::vector< std::string > **)&_swig_go_0; 
  
  delete arg1;
  
}


#ifdef __cplusplus
}
#endif

