# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.3.0
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _pdje_python
else:
    import _pdje_python

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


FULL_PRE_RENDER = _pdje_python.FULL_PRE_RENDER
HYBRID_RENDER = _pdje_python.HYBRID_RENDER
FULL_MANUAL_RENDER = _pdje_python.FULL_MANUAL_RENDER
class PDJE(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, rootPath):
        _pdje_python.PDJE_swiginit(self, _pdje_python.new_PDJE(rootPath))
    __swig_destroy__ = _pdje_python.delete_PDJE
    player = property(_pdje_python.PDJE_player_get, _pdje_python.PDJE_player_set)

    def InitPlayer(self, mode, td, FrameBufferSize):
        return _pdje_python.PDJE_InitPlayer(self, mode, td, FrameBufferSize)

    def GetNoteObjects(self, td, ObjectSetCallback):
        return _pdje_python.PDJE_GetNoteObjects(self, td, ObjectSetCallback)

    def SearchMusic(self, Title, composer, bpm=-1):
        return _pdje_python.PDJE_SearchMusic(self, Title, composer, bpm)

    def SearchTrack(self, Title):
        return _pdje_python.PDJE_SearchTrack(self, Title)

# Register PDJE in _pdje_python:
_pdje_python.PDJE_swigregister(PDJE)

